### ISSUE TITLE
NullPointerException when swapping world from main menu

### ISSUE THREAD

**Issue by Bialogs** [Devin-Holland/group-tileman#4]
Menu before logged in

```
[Client] WARN net.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException
	at com.grouptilemanonline.TilemanModePlugin.onConfigChanged(TilemanModePlugin.java:195)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:791)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:808)
	at net.runelite.client.config.ConfigInvocationHandler.invoke(ConfigInvocationHandler.java:172)
	at com.sun.proxy.$Proxy46.lastWorld(Unknown Source)
	at net.runelite.client.plugins.defaultworld.DefaultWorldPlugin.onWorldChanged(DefaultWorldPlugin.java:100)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:189)
	at client.ln(client.java:49959)
	at hq.au(hq.java:2204)
	at lv.aq(lv.java:438)
	at client.br(client.java:1100)
	at br.is(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Bialogs** [comment]
5ddcab15abf35f63388c5f1a5a082896848af658
